server:
  port: 8090

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true #to be commented
  jpa:
    defer-datasource-initialization: true
